/* Generated by Yosys 0.37 (git sha1 a5c7f69ed8f, gcc 13.2.1 -march=x86-64 -mtune=generic -O2 -fno-plt -fexceptions -fstack-clash-protection -fcf-protection -ffile-prefix-map=/build/yosys/src=/usr/src/debug/yosys -fPIC -Os) */

(* hdlname = "\\counter" *)
(* top =  1  *)
(* src = "counter.v:1.1-28.10" *)
module counter(clk, rst_n, start, stop, count);
  wire _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  wire _10_;
  wire _11_;
  wire _12_;
  wire _13_;
  wire _14_;
  wire _15_;
  wire _16_;
  wire _17_;
  wire _18_;
  (* force_downto = 32'd1 *)
  (* src = "counter.v:23.16-23.26|/usr/bin/../share/yosys/techmap.v:270.23-270.24" *)
  wire [5:0] _19_;
  wire _20_;
  wire _21_;
  wire _22_;
  wire _23_;
  wire _24_;
  wire _25_;
  (* src = "counter.v:2.17-2.20" *)
  input clk;
  wire clk;
  (* src = "counter.v:6.23-6.28" *)
  output [5:0] count;
  wire [5:0] count;
  (* src = "counter.v:3.17-3.22" *)
  input rst_n;
  wire rst_n;
  (* src = "counter.v:4.17-4.22" *)
  input start;
  wire start;
  (* src = "counter.v:9.5-9.10" *)
  wire state;
  (* src = "counter.v:5.17-5.21" *)
  input stop;
  wire stop;
  (* src = "counter.v:10.11-10.14" *)
  wire [5:0] val;
  INV_X1 _26_ (
    .A(_19_[0]),
    .ZN(_07_)
  );
  INV_X1 _27_ (
    .A(rst_n),
    .ZN(_08_)
  );
  NOR2_X1 _28_ (
    .A1(state),
    .A2(val[0]),
    .ZN(_09_)
  );
  AOI211_X1 _29_ (
    .A(_08_),
    .B(_09_),
    .C1(state),
    .C2(_07_),
    .ZN(_00_)
  );
  AND3_X1 _30_ (
    .A1(state),
    .A2(val[1]),
    .A3(val[0]),
    .ZN(_10_)
  );
  AOI21_X1 _31_ (
    .A(val[1]),
    .B1(val[0]),
    .B2(state),
    .ZN(_11_)
  );
  NOR3_X1 _32_ (
    .A1(_08_),
    .A2(_10_),
    .A3(_11_),
    .ZN(_01_)
  );
  AND4_X1 _33_ (
    .A1(state),
    .A2(val[2]),
    .A3(val[1]),
    .A4(val[0]),
    .ZN(_12_)
  );
  OAI21_X1 _34_ (
    .A(rst_n),
    .B1(_10_),
    .B2(val[2]),
    .ZN(_13_)
  );
  NOR2_X1 _35_ (
    .A1(_12_),
    .A2(_13_),
    .ZN(_02_)
  );
  OAI21_X1 _36_ (
    .A(rst_n),
    .B1(_12_),
    .B2(val[3]),
    .ZN(_14_)
  );
  AOI21_X1 _37_ (
    .A(_14_),
    .B1(_12_),
    .B2(val[3]),
    .ZN(_03_)
  );
  AND3_X1 _38_ (
    .A1(val[4]),
    .A2(val[3]),
    .A3(_12_),
    .ZN(_15_)
  );
  AOI21_X1 _39_ (
    .A(val[4]),
    .B1(val[3]),
    .B2(_12_),
    .ZN(_16_)
  );
  NOR3_X1 _40_ (
    .A1(_08_),
    .A2(_15_),
    .A3(_16_),
    .ZN(_04_)
  );
  OAI21_X1 _41_ (
    .A(rst_n),
    .B1(_15_),
    .B2(val[5]),
    .ZN(_17_)
  );
  AOI21_X1 _42_ (
    .A(_17_),
    .B1(_15_),
    .B2(val[5]),
    .ZN(_05_)
  );
  OAI21_X1 _43_ (
    .A(rst_n),
    .B1(start),
    .B2(state),
    .ZN(_18_)
  );
  NOR2_X1 _44_ (
    .A1(stop),
    .A2(_18_),
    .ZN(_06_)
  );
  (* src = "counter.v:19.1-24.4" *)
  DFF_X1 _45_ (
    .CK(clk),
    .D(_00_),
    .Q(val[0]),
    .QN(_19_[0])
  );
  (* src = "counter.v:19.1-24.4" *)
  DFF_X1 _46_ (
    .CK(clk),
    .D(_01_),
    .Q(val[1]),
    .QN(_25_)
  );
  (* src = "counter.v:19.1-24.4" *)
  DFF_X1 _47_ (
    .CK(clk),
    .D(_02_),
    .Q(val[2]),
    .QN(_24_)
  );
  (* src = "counter.v:19.1-24.4" *)
  DFF_X1 _48_ (
    .CK(clk),
    .D(_03_),
    .Q(val[3]),
    .QN(_23_)
  );
  (* src = "counter.v:19.1-24.4" *)
  DFF_X1 _49_ (
    .CK(clk),
    .D(_04_),
    .Q(val[4]),
    .QN(_22_)
  );
  (* src = "counter.v:19.1-24.4" *)
  DFF_X1 _50_ (
    .CK(clk),
    .D(_05_),
    .Q(val[5]),
    .QN(_21_)
  );
  (* src = "counter.v:12.1-17.4" *)
  DFF_X1 _51_ (
    .CK(clk),
    .D(_06_),
    .Q(state),
    .QN(_20_)
  );
  assign _19_[5:1] = val[5:1];
  assign count = val;
endmodule
